# Generated by Django 5.0.6 on 2024-05-31 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsk_mng_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='daily_container',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='is_complete',
        ),
        migrations.DeleteModel(
            name='DailyList',
        ),
    ]
